
name: AWS Prod Deployment
on:
    push:
      branches:
        - main
permissions:
  id-token: write
  contents: read
jobs:
    deploy-prod:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Setup Go
          uses: actions/setup-go@v5

        - name: Setup AWS SAM
          uses: aws-actions/setup-sam@v2

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: us-east-2
            role-to-assume: arn:aws:iam::658340567265:role/github-actions-role
            role-session-name: GithubActionsSession
        
        - name: Build App
          run: make build && make zip && sam build --use-container
        
        - name: Sam Deploy
          run: sam deploy --config-env prod --no-confirm-changeset --no-fail-on-empty-changeset